# Generated by Django 5.0 on 2024-02-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='titr',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=False, upload_to='profile/'),
        ),
    ]
