# Generated by Django 5.0 on 2024-02-15 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_image_alter_post_created_alter_post_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',)},
        ),
    ]
